mobile error codes - auth bug
fugitivelabs/yote pull request #217
Opened 2021-10-11 19:07 UTC by WesJourdan

NOTE: to be merged into open PR #214 

- Update login and register methods on server to return user and token, rm unused mobileLogin method.
- Update mobile auth store to deal with server returned tokens.
- Remove login action from mobile register page (no longer necessary, user is logged in on register).
- Clean up a couple of small things I noticed.

2021-10-11 19:13 UTC, austincline09 commented on server/resources/user/sessionController.js
> +        console.log('MOBILE REQUEST BEING FULFILED LIKE A BAAAUUUUCE');
lol

2021-10-11 19:15 UTC, WesJourdan commented on server/resources/user/sessionController.js
> +        console.log('MOBILE REQUEST BEING FULFILED LIKE A BAAAUUUUCE');
lmao whoops!

2021-10-11 19:16 UTC, WesJourdan commented on server/resources/user/sessionController.js
> +        console.log('MOBILE REQUEST BEING FULFILED LIKE A BAAAUUUUCE');
Fixed

2021-10-12 13:34 UTC, grantfowler requested changes
small change

2021-10-12 13:34 UTC, grantfowler commented on mobile/Yote/js/AuthNavigator.js
> +                , animationTypeForReplace: loggedInUser ? 'pop' : 'push'
+1

2021-10-12 13:34 UTC, grantfowler commented on mobile/Yote/js/resources/user/authStore.js
> +    userInfo.mobile = true;
can you add this field to the register action too?

2021-10-12 13:44 UTC, grantfowler approved these changes

2021-10-12 13:44 UTC, merged